### ISSUE TITLE
官网报名注册提示系统内部错误

### ISSUE THREAD

**Issue by SergeyuiL** [AIR-DISCOVER/ICRA2024-Sim2Real-AXS#7]
Join Challenge时需要Edit profile，但是edit后无法保存，提示系统内部出现错误，无法完成报名
![image](https://github.com/AIR-DISCOVER/ICRA2024-Sim2Real-AXS/assets/109088638/ad30ad95-3c42-437f-97e8-5feeae8912ce)

**Comment by jzndd** [comment]
同样的问题，已经发邮件给组委会邮箱，但是没有得到回复，请问您解决了吗
